- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
 
  tasks:
  - name: Update the repository cache
    apt:
      update_cache: yes

  - name: Update all packages
    apt:
      upgrade: yes

  - name: Install docker packages
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - pass
      state: latest
      update_cache: yes

  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: yes

  - name: Install docker
    apt:
      name: docker-ce
      state: latest
      update_cache: yes
    notify: Start docker on boot

  - name: Add remote "ubuntu" user to "docker" group
    user:
      name: "ubuntu"
      group: "docker"
      append: yes

  - name: Install docker-compose
    apt:
      name: docker-compose
      state: latest
      update_cache: yes
  
  - name: Remove useless apt packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  handlers:
  - name: Start docker on boot
    systemd:
      name: docker
      state: started
      enabled: yes